name: Python Check

on: [push, pull_request]
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Python Check
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.10.7
    - run: pip install --upgrade pip
    - run: pip install "black<23" pylint==v3.0.0a3
    - run: black --diff --check $(git ls-files 'hopre/*.py')
